### ISSUE TITLE
Add Vue.js, Facebook, ...

### ISSUE THREAD

**Issue by maxdevjs** [cutenode/good-first-issue#8]
Added a few orgs to my fork:

- [Angular](https://github.com/maxdevjs/good-first-issue/tree/angular)
- [Facebook](https://github.com/maxdevjs/good-first-issue/tree/facebook)
- [Vue.js](https://github.com/maxdevjs/good-first-issue/tree/vuejs)

Hints, suggestions, is this done the right way, useful...? :)

**Comment by bnb** [comment]
Hey, thanks for the work!

Some feedback:

- In your searches, you don't need to include `sort:updated-desc` since that's included in the query to `@octokit/rest.js`.
- Facebook is definitely an interesting idea, and one I'd not thought about! I really like the concept, though I think we may want to have a slightly more comprehensive description because it's an org with multiple facets 😄

**Comment by maxdevjs** [comment]
Thanks for clarifications. 

- ops... about `sort:updated-desc` I did a paste & copy of `electron` project, not `node`, should `electron`  (and `gutenberg`) be changed too? 
- I agree, again... had this doubt too. And what would be better? Add orgs as a whole (example: `org:facebook` and not just `repo:org:facebook/react`, as per `org:nodejs`) or specific repos (`repo:angular/angular`, as per `repo:microsoft/vscode`, etc)?

**Comment by bnb** [comment]
Indeed, #10 has now landed.

I'd like to keep things centralized into specific commands. I'm not opposed to having unique commands for `facebook`, `react, `jest`, and so on.

Node.js is an org but it's a weird org in that everything in it is around Node.js as a project... so they're all basically the same project. Someone who is going to be interested in a first contribution to Node.js can contribute to any of the repos.

Facebook has multiple projects that span different technologies... someone who wants to contribute to React probably isn't interested in contributing to [facebook/mysql-5.6](https://github.com/facebook/mysql-5.6).

Separating those concerns out and having per-project commands makes sense IMO... regardless of whether or not a project is an org or a repo. Other examples of orgs that are projects I can think of:

- Babel
- Electron (hey, there's already a command for this one!)
- webpack
- Gatsby

That said, I think it's a nifty a idea and something we should explore to have org commands like `facebook`, `microsoft`, `github`, `google`, `airbnb`, and so on!

Perhaps this syntax could be used for diverse (rather than single-focus) orgs:

```
# Syntax
good-first-issue <org>/<repo>

# Examples
good-first-issue facebook/react
good-first-issue microsoft/azuredatastudio
good-first-issue github/gitignore
```

Does that make sense?

**Comment by bnb** [comment]
Going to close this 👍
